const ERROR_HEADER = '[ERROR]';

/** 에러 메세지 상수화 */
export const ERROR_MESSAGE = Object.freeze({
  // 입력값 검증 에러 메세지
  ERROR_MESSAGE_INVALID_INPUT: `${ERROR_HEADER} 입력값이 올바르지 않습니다.`,
  ERROR_MESSAGE_NULL_INPUT: `${ERROR_HEADER} null 값은 입력할 수 없습니다.`,
  ERROR_MESSAGE_UNDEFINED_INPUT: `${ERROR_HEADER} undefined 값은 입력할 수 없습니다.`,
  ERROR_MESSAGE_INVALID_FORMAT: `${ERROR_HEADER} 잘못된 형식입니다.`,

  // 숫자 관련 에러 메세지
  ERROR_MESSAGE_NOT_A_NUMBER: `${ERROR_HEADER} 숫자가 아닌 값이 포함되어 있습니다.`,
  ERROR_MESSAGE_CANNOT_CONVERT_NUMBER: `${ERROR_HEADER} 숫자로 변환할 수 없는 값이 포함되어 있습니다.`,
  ERROR_MESSAGE_NEGATIVE_NUMBER: `${ERROR_HEADER} 음수는 입력할 수 없습니다.`,
  ERROR_MESSAGE_INVALID_NUMBER_NEGATIVE: `${ERROR_HEADER} 음수인 숫자는 입력할 수 없습니다.`,
  ERROR_MESSAGE_EMPTY_NUMBER: `${ERROR_HEADER} 빈 숫자가 포함되어 있습니다.`,
  ERROR_MESSAGE_INVALID_NUMBER_LENGTH: `${ERROR_HEADER} 숫자의 길이가 올바르지 않습니다.`,
  ERROR_MESSAGE_INVALID_NUMBER_RANGE: `${ERROR_HEADER} 숫자의 범위가 올바르지 않습니다.`,
  ERROR_MESSAGE_NUMBER_OVERFLOW: `${ERROR_HEADER} 숫자가 너무 큽니다.`,
  ERROR_MESSAGE_NUMBER_TOO_LARGE: `${ERROR_HEADER} 허용 범위를 초과한 숫자입니다.`,
  ERROR_MESSAGE_DECIMAL_NOT_ALLOWED: `${ERROR_HEADER} 소수점은 허용되지 않습니다.`,
  ERROR_MESSAGE_ONLY_INTEGER_ALLOWED: `${ERROR_HEADER} 정수만 입력 가능합니다.`,

  // 구분자 관련 에러 메세지
  ERROR_MESSAGE_ONLY_SEPARATOR: `${ERROR_HEADER} 구분자만 입력되었습니다.`,
  ERROR_MESSAGE_STARTS_WITH_SEPARATOR: `${ERROR_HEADER} 구분자로 시작할 수 없습니다.`,
  ERROR_MESSAGE_ENDS_WITH_SEPARATOR: `${ERROR_HEADER} 구분자로 끝날 수 없습니다.`,
  ERROR_MESSAGE_CONSECUTIVE_SEPARATORS: `${ERROR_HEADER} 연속된 구분자가 있습니다.`,
  ERROR_MESSAGE_INVALID_SEPARATOR_LENGTH: `${ERROR_HEADER} 구분자의 길이가 올바르지 않습니다.`,
  ERROR_MESSAGE_INVALID_SEPARATOR_TYPE: `${ERROR_HEADER} 타입이 올바르지 않습니다.`,

  // 커스텀 구분자 관련 에러 메세지
  ERROR_MESSAGE_NOT_INCLUDE_SEPARATOR: `${ERROR_HEADER} 사용자 정의 구분자가 포함되어 있지 않습니다.`,
  ERROR_MESSAGE_CUSTOM_SEPARATOR_MISSING: `${ERROR_HEADER} 커스텀 구분자가 비어있습니다.`,
  ERROR_MESSAGE_CUSTOM_SEPARATOR_INVALID_FORMAT: `${ERROR_HEADER} 커스텀 구분자 형식이 올바르지 않습니다.`,
  ERROR_MESSAGE_CUSTOM_SEPARATOR_NO_NEWLINE: `${ERROR_HEADER} 커스텀 구분자 뒤에 개행 문자가 없습니다.`,
  ERROR_MESSAGE_CUSTOM_SEPARATOR_NO_NUMBERS: `${ERROR_HEADER} 커스텀 구분자 뒤에 숫자가 없습니다.`,
  ERROR_MESSAGE_INVALID_SLASH_COUNT: `${ERROR_HEADER} 슬래시는 정확히 2개여야 합니다.`,

  // 문자 관련 에러 메세지
  ERROR_MESSAGE_CONTAINS_WHITESPACE: `${ERROR_HEADER} 공백이 포함되어 있습니다.`,
  ERROR_MESSAGE_INVALID_SPECIAL_CHARACTER: `${ERROR_HEADER} 허용되지 않는 특수문자가 포함되어 있습니다.`,
  ERROR_MESSAGE_INVALID_CHARACTER: `${ERROR_HEADER} 허용되지 않는 문자가 포함되어 있습니다.`,
  ERROR_MESSAGE_EMOJI_NOT_ALLOWED: `${ERROR_HEADER} 이모지는 입력할 수 없습니다.`,
  ERROR_MESSAGE_MULTIPLE_LINES: `${ERROR_HEADER} 여러 줄 입력은 허용되지 않습니다.`,

  // 값 관련 에러 메세지
  ERROR_MESSAGE_INVALID_VALUE_LENGTH: `${ERROR_HEADER} 값의 길이가 올바르지 않습니다.`,
  ERROR_MESSAGE_INVALID_VALUE_NUMBER: `${ERROR_HEADER} 값이 모두 숫자입니다.`,
  ERROR_MESSAGE_INVALID_VALUE_STRING: `${ERROR_HEADER} 값이 모두 문자열입니다.`,
});
